version: "3.8"
services:

  init-geth:
    image: ethereum/client-go:$GETH_VERSION
    container_name: lukso-geth-init
    volumes:
      - $EXECUTION_DATA_VOLUME:/execution_data
      - $CONFIGS_VOLUME:/configs
    command: >
      --datadir=/execution_data init /configs/shared/genesis.json

  geth:
    image: ethereum/client-go:$GETH_VERSION
    container_name: lukso-geth
    depends_on:
      - init-geth
    volumes:
      - $EXECUTION_DATA_VOLUME:/execution_data
      - $CONFIGS_VOLUME:/configs
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    command: >
      --config /configs/geth/geth.toml
      --datadir=/execution_data
      --ws
      --ws.api "eth,net,web3,engine"
      --ws.addr 0.0.0.0
      --ws.origins "*"
      --http
      --http.api "eth,net,web3,engine"
      --http.addr "0.0.0.0"
      --http.corsdomain "*"
      --http.vhosts "*"
      --ipcdisable
      --metrics
      --metrics.addr "0.0.0.0"
      --authrpc.jwtsecret /configs/jwt.hex
     # --ethstats "${NODE_NAME}:${ETH_STATS_SECRET}@${ETH_STATS_ADDRESS}"
     # Add your custom flags here:
     # https://geth.ethereum.org/docs/fundamentals/command-line-options
    network_mode: host

  prysm_beacon:
    image: prysmaticlabs/prysm-beacon-chain:$PRYSM_BEACON_VERSION
    container_name: prysm_beacon
    depends_on:
      - geth
    volumes:
      - $CONSENSUS_DATA_VOLUME:/consensus_data
      - $CONFIGS_VOLUME:/configs
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    command: >
      --accept-terms-of-use
      --config-file=/configs/prysm/prysm.yaml
      --genesis-state=/configs/shared/genesis.ssz
      --chain-config-file=/configs/shared/config.yaml
      --datadir=/consensus_data
      --execution-endpoint=http://localhost:8551
      --jwt-secret=/configs/jwt.hex
      --suggested-fee-recipient $FEE_RECIPIENT
     # Add your custom flags here.
     # Docs: https://docs.prylabs.network/docs/prysm-usage/parameters#beacon-node-flags
    network_mode: host
  
  prysm_validator_import:
    image: prysmaticlabs/prysm-validator:v4.0.3
    container_name: prysm_validator_import
    volumes:
      - $KEYSTORE_VOLUME:/keystore
      - $VALIDATOR_DATA_VOLUME:/validator_data
      - $CONFIGS_VOLUME:/configs
      - $TMP_VOLUME:/tmp/secrets
    command: >
      accounts import
      --accept-terms-of-use
      --keys-dir=/keystore
      --wallet-dir=/keystore/prysm
      --wallet-password-file=/tmp/secrets/password.txt
      --account-password-file=/tmp/secrets/password.txt

  prysm_validator:
    image: prysmaticlabs/prysm-validator:v4.0.3
    container_name: prysm_validator
    depends_on:
      prysm_beacon:
        condition: service_started
      prysm_validator_import:
        condition: service_completed_successfully
    volumes:
      - $KEYSTORE_VOLUME:/keystore
      - $VALIDATOR_DATA_VOLUME:/validator_data
      - $CONFIGS_VOLUME:/configs
      - $TMP_VOLUME:/tmp/secrets
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    command: >
      --accept-terms-of-use
      --datadir /validator_data
      --wallet-dir /keystore/prysm
      --wallet-password-file /tmp/secrets/password.txt
      --chain-config-file /configs/shared/config.yaml
      --monitoring-host 0.0.0.0
      --grpc-gateway-host 0.0.0.0
      --rpc-host 0.0.0.0
      --suggested-fee-recipient $FEE_RECIPIENT
    network_mode: host
    logging:
      driver: "local"
      options:
        max-size: "100m"